name: deploy to vardrz.github.io

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 * * * *" # tiap jam cek artikel baru
  workflow_dispatch:
  repository_dispatch:
    types: [new-article]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Deploy to vardrz.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAT_VARD }}
          external_repository: vardrz/vardrz.github.io
          publish_branch: main
          publish_dir: ./dist
          cname: vard.is-a.dev
          keep_files: false
          commit_message: "chore: deploy from vardrz/react_porto ${{ github.sha }}"
